pipeline {
    agent any

    environment {
        APP_EC2_IP = '10.0.2.55' // private EC2 IP
    }

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/agiratech-Mahima/Mern_app.git'
            }
        }

        stage('Build and Push Backend') {
            steps {
                dir('backend') {
                    withCredentials([
                        usernamePassword(credentialsId: 'dockerhubCredentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS'),
                        string(credentialsId: 'MONGO_URI', variable: 'MONGO_URI'),
                        string(credentialsId: 'JWT_SECRET', variable: 'JWT_SECRET')
                    ]) {
                        sh '''
                        docker login -u $DOCKER_USER -p $DOCKER_PASS
                        docker build -t $DOCKER_USER/mern_app:backend .
                        docker push $DOCKER_USER/mern_app:backend
                        '''
                    }
                }
            }
        }

        stage('Deploy to App EC2') {
            steps {
                sshagent (credentials: ['app-ec2-key']) {
                    withCredentials([
                        usernamePassword(credentialsId: 'dockerhubCredentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS'),
                        string(credentialsId: 'MONGO_URI', variable: 'MONGO_URI'),
                        string(credentialsId: 'JWT_SECRET', variable: 'JWT_SECRET')
                    ]) {
                        sh """
                        ssh -o StrictHostKeyChecking=no ubuntu@$APP_EC2_IP '
                            docker login -u $DOCKER_USER -p $DOCKER_PASS &&
                            docker stop backend || true &&
                            docker rm backend || true &&
                            docker pull $DOCKER_USER/mern_app:backend &&
                            docker run -d --name backend \\
                              --network host \\
                              -e MONGO_URI="$MONGO_URI" \\
                              -e JWT_SECRET="$JWT_SECRET" \\
                              $DOCKER_USER/mern_app:backend
                        '
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Build and Deployment Successful!'
        }
        failure {
            echo 'Build or Deployment Failed!'
        }
    }
}

